//
// Generated by makeclass.rb on Sun Oct 04 15:08:43 +1300 2009.
// Copyright Nicholas Chapman.
//
#pragma once


namespace Winter
{


class LanuageTests
{
public:
	LanuageTests();
	~LanuageTests();
	
	static void run();
private:
};


}


